# Generated by Django 4.2.7 on 2023-11-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_booking_created_alter_contact_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='paymentid',
            field=models.CharField(default='DefaultValue', max_length=50),
            preserve_default=False,
        ),
    ]
