# Generated by Django 4.2.7 on 2023-11-27 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_booking_paymentid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='paymentid',
            new_name='paymentId',
        ),
    ]
