# Generated by Django 4.2.7 on 2023-11-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_paymentid_booking_paymentid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='booking',
            name='amt',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
